version: '3.8'

services:
  client:
    image: webcrud-client
    container_name: webcrud-client
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - client-server
    environment:
      - REACT_APP_API_URL=http://server:9000
      
  server:
    image: webcrud-server
    container_name: webcrud-server
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/webcrud
    networks:
      - client-server
      - server-db

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    networks:
      - server-db

volumes:
  mongo-data:

networks:
  client-server:
  server-db:
