version: '3.0'

services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    networks:
      - mern-app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
