version: '3.8'

services:
  client:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - hant-network
      
  server:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/webcrud
    networks:
      - hant-network

  mongo:
    build: 
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - mongo-data:/data/db
    networks:
      - hant-network

volumes:
  mongo-data:

networks:
  hant-network:
