---
- name: Setup Docker
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common

# - name: Setup a 3-tier web application
#   hosts: all
#   become: true
#   gather_facts: true

#   roles:
#     - common
#     - web
#     - api
#     - db

- name: Setup Web service 
  hosts: all
  become: true
  gather_facts: true

  roles:
    - web

- name: Setup API + DB service
  hosts: all
  become: true
  gather_facts: true

  roles:
    - api
    - db