- name: Gather Docker network facts
  docker_network_facts:
    filters:
      name: hant_default
  register: docker_network
  become: true

- name: Create Docker network hant_default if it doesn't exist
  docker_network:
    name: hant_default
    state: present
  when: docker_network.networks | length == 0
  become: true

- name: Pull hant-api-service Docker image
  docker_image:
    name: hant-api-service
    state: present

- name: Run hant-api-service container
  docker_container:
    name: api-container
    image: hant-api-service
    state: started
    ports:
      - "8080:8080"
    networks:
      - name: hant_default
